<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="149525" started-at="2018-06-15T12:09:24Z" finished-at="2018-06-15T12:11:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="149525" started-at="2018-06-15T12:09:24Z" finished-at="2018-06-15T12:11:53Z">
      <class name="com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage@61009542]" name="setup" is-config="true" duration-ms="11003" started-at="2018-06-15T17:39:24Z" finished-at="2018-06-15T17:39:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage@61009542]" name="beforeMethod" is-config="true" duration-ms="4" started-at="2018-06-15T17:39:35Z" finished-at="2018-06-15T17:39:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage.verifyItemDetails() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifyItemDetails()[pri:0, instance:com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage@61009542]" name="verifyItemDetails" duration-ms="135671" started-at="2018-06-15T17:39:35Z" finished-at="2018-06-15T17:41:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage.verifyItemDetails(TC002_VerifyItemDetailsInCostCenterPage.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyItemDetails -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage@61009542]" name="afterMethod" is-config="true" duration-ms="305" started-at="2018-06-15T17:41:51Z" finished-at="2018-06-15T17:41:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyItemDetails status=FAILURE method=TC002_VerifyItemDetailsInCostCenterPage.verifyItemDetails()[pri:0, instance:com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage@61009542] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage@61009542]" name="endTest" is-config="true" duration-ms="2527" started-at="2018-06-15T17:41:51Z" finished-at="2018-06-15T17:41:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- com.c2info.RMS_CostCenterApproverTCs.TC002_VerifyItemDetailsInCostCenterPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
